blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions | سوالات عمومی
    url: https://github.com/saeedmasoudie/pywarp/discussions
    about: For help, troubleshooting, or general discussion | برای کمک، رفع اشکال یا بحث عمومی
