name: Build & Release PyWarp

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Read Version
        id: version
        shell: bash
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka==1.9.5

      - name: Build Executable
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.version }}"
          python -m nuitka main.py `
            --standalone `
            --onefile `
            --disable-console `
            --enable-plugin=pyside6 `
            --nofollow-imports `
            --noinclude-pytest-mode=nofollow `
            --noinclude-unittest-mode=nofollow `
            --nofollow-import-to=tkinter,test,pydoc `
            --include-data-dir=assets=assets `
            --include-qt-plugins=all `
            --windows-icon-from-ico=assets/logo.ico `
            --output-dir=dist `
            --output-filename="pywarp-windows-v$version" `
            --windows-company-name="PyWarp" `
            --windows-product-name="PyWarp" `
            --windows-file-version="$version" `
            --windows-product-version="$version" `
            --remove-output `
            --assume-yes-for-downloads

      - name: Zip Executable
        run: |
          cd dist
          powershell Compress-Archive -Path pywarp-windows-v${{ steps.version.outputs.version }}.exe -DestinationPath pywarp-windows-v${{ steps.version.outputs.version }}.zip

      - uses: actions/upload-artifact@v4
        with:
          name: pywarp-windows
          path: dist/pywarp-windows-v${{ steps.version.outputs.version }}.zip

  build-linux-macos:
    name: Build Linux/macOS
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: build-windows
    steps:
      - uses: actions/checkout@v3

      - name: Read Version
        id: version
        shell: bash
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka==1.9.5

      - name: Build Executable
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          PLATFORM="${{ matrix.os }}"
          OUTPUT="pywarp-${PLATFORM}-v$VERSION"
          FLAGS="--standalone --onefile --remove-output --disable-console --enable-plugin=pyside6"
          if [[ "$PLATFORM" == "macos-latest" ]]; then
            FLAGS+=" --macos-app-icon=assets/logo.icns --macos-create-app-bundle"
          fi
          python -m nuitka main.py $FLAGS \
            --include-data-dir=assets=assets \
            --output-filename="$OUTPUT"

      - name: Zip Executable
        run: zip pywarp-${{ matrix.os }}-v${{ steps.version.outputs.version }}.zip pywarp-${{ matrix.os }}-v${{ steps.version.outputs.version }}

      - uses: actions/upload-artifact@v4
        with:
          name: pywarp-${{ matrix.os }}
          path: pywarp-${{ matrix.os }}-v${{ steps.version.outputs.version }}.zip

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux-macos]
    steps:
      - uses: actions/checkout@v3

      - name: Read Version
        id: version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract Changelog for Release
        id: changelog
        run: |
          VERSION="v${{ steps.version.outputs.version }}"
          awk -v ver="$VERSION" '
            $0 ~ "^## " ver {flag=1; next}
            flag && /^## / {exit}
            flag {print}
          ' CHANGELOG.md > RELEASE_NOTES.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: PyWarp v${{ steps.version.outputs.version }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
          files: |
            artifacts/pywarp-windows/*.zip
            artifacts/pywarp-ubuntu-latest/*.zip
            artifacts/pywarp-macos-latest/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
